AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Render API - render::render
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  RenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: render.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/micronaut-freemarker-aws-example-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MicronautFreemarkerAwsExampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MicronautFreemarkerAwsExampleApi
