micronaut:
  application:
    name: micronaut-freemarker-aws-example

  http:
    services:
      my-client:
        url: "https://xk2ikhvjwe.execute-api.us-east-1.amazonaws.com"
        path: "/Prod/jeff"
    client:
      read-timeout: 30s

  views:
    freemarker:
      enabled: true

  security:
    enabled: disabled

endpoints:
  all:
    sensitive: false
    enabled: true