micronaut:
  application:
    name: micronaut-freemarker-aws-example

  http:
    services:
      my-client:
        url: "${APIGW_BASE_URL:`http://localhost:8080`}"
        path: "/"

  views:
    freemarker:
      enabled: true

  security:
    enabled: disabled

endpoints:
  all:
    sensitive: false
    enabled: true