micronaut:
  application:
    name: micronaut-freemarker-aws-example

  http:
    services:
      my-client:
        url: "${APIGW_BASE_URL:`https://xk2ikhvjwe.execute-api.us-east-1.amazonaws.com/Prod`}"
#        url: "${APIGW_BASE_URL:`http://localhost:8080`}"
    client:
      read-timeout: 30s

  views:
    freemarker:
      enabled: true

  security:
    enabled: disabled

endpoints:
  all:
    sensitive: false
    enabled: true