---
micronaut:
  application:
    name: micronaut-freemarker-aws-example

---

micronaut:
  views:
#    folder: file:/Users/jeff/dev/cci/micronaut-pocs/phoenix/render/src/main/resources/views
    freemarker:
      enabled: true
#      template:
#        Configuration:

  router:
    static-resources:
      public:
          enabled: true
          paths: classpath:public
          mapping: /public/**

  security:
    enabled: disabled

endpoints:
  all:
    sensitive: false
    enabled: true